#!/bin/bash

in_dir="src"
out_dir="target/debug"
#web_dir="../../www/helloki_org"


clear

# clean up
# --------
echo "> removing old data..."
rm -rf "${out_dir:?}/"*
mkdir -p $out_dir
#rm -rf "${web_dir:?}"

# copy everything
# ---------------
echo "> copying src..."
cp -r "${in_dir}"/* ${out_dir}

# remove typescript
# -----------------
echo "> removing ts files..."
find "${out_dir}" -type f -name "*.ts" -exec rm {} \;


# build typescript
# ----------------
echo "> building typescript..."
tsc || exit 1

# copy to web
# ----------
#echo "> copying data to web..."
#cp -r "${out_dir}" "${web_dir}"

# reloading the page
# ------------------
echo "> reloading the page..."
browser-sync reload


echo "Done..."
echo


