#!/bin/env bash


file_name=$1
[ -z "$file_name" ] && read -p "File-Name: " file_name
class_name=$2
[ -z "$class_name" ] && read -p "Class-Name: " class_name

comp_path="src/components/$file_name"
templ_path="whell_tools/templ/touch"

templ_css_file_name="css_templ.css"
templ_html_file_name="html_templ.html"
templ_ts_file_name="ts_templ.ts"
templ_class_name="TemplClassName"

echo "> trying to touch component '$file_name' at path '$comp_path'"

# validate
# --------
[ -d "$comp_path" ] && { echo "> failed to touch: directory '$comp_path' already exists!" ; exit 1 ; }

# create component dir
# --------------------
mkdir -p "$comp_path"

# create files
# ------------
cp "$templ_path/$templ_css_file_name" "$comp_path/$file_name.css" || exit 1
cp "$templ_path/$templ_html_file_name" "$comp_path/$file_name.html" || exit 1
cat "$templ_path/$templ_ts_file_name" | sed "s/$templ_class_name/$class_name/" > "$comp_path/$file_name.ts" || exit 1

echo "> successfully touched component '$file_name' at path '$comp_path'"
