#!/bin/env bash


old_name=$1
[ -z "$old_name" ] && read -rp "Old-Name: " old_name
new_name=$2
[ -z "$new_name" ] && read -rp "New-Name: " new_name

old_dir="src/components/$old_name"
new_dir="src/components/$new_name"

[ -d "$old_dir" ] || { echo "> failed to find directory ${old_dir}" ; exit 1 ; }
[ -d "$new_dir" ] && { echo "> component with name ${new_name} already exists at ${new_dir}" ; exit 1 ; }

echo "> moving directory..."
mv "$old_dir" "$new_dir" || exit 1

echo "> renaming files..."
rename "$old_name" "$new_name" "$new_dir"/* || exit 1

echo "> successfully renamed component '$old_name' to '$new_name'"
