#!/bin/bash

sh_path=$(dirname $0)
base_dir="$sh_path/.."
in_dir="$base_dir/src"
out_dir="$base_dir/target/debug"

# handle input
# ------------
positional_args=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        "-b"|"--base-dir")
            base_dir="$2"
            shift 2
            ;;
        "-r"|"--reload")
            should_reload="YES"
            shift
            ;;
    esac
done

set -- "${positional_args[@]}"


echo "> start building whell..."


# clean up
# --------
echo "> removing old data..."
rm -rf "${out_dir:?}/"*
mkdir -p $out_dir

# copy everything
# ---------------
echo "> copying src..."
cp -r "${in_dir}"/* ${out_dir}

# remove typescript
# -----------------
echo "> removing ts files..."
find "${out_dir}" -type f -name "*.ts" -exec rm {} \;


# build typescript
# ----------------
echo "> building typescript..."
tsc --build "$base_dir" || exit 1

# reloading the page
# ------------------
if [[ -n $should_reload ]]; then
    echo "> reloading the page..."
    browser-sync reload
fi


echo "> done bulding whell..."
echo


